### ISSUE TITLE
Release for attrs version pinning

### ISSUE THREAD

**Issue by AbdealiJK** [flake8-implicit-str-concat/flake8-implicit-str-concat#29]
Hi,
I've been using this package for the past 2-3 months.
We've been getting broken requirements from pip for a while due to the issue solved by:
https://github.com/keisheiled/flake8-implicit-str-concat/commit/c669d62a164ffe4c44d162806ddf71b2e21971e5

Is there a release planned to push this fix out ?

**Comment by hugovk** [comment]
@keisheiled Hi! If you add me to PyPI (I'm also hugovk there) I'd be happy to take care of a new release.

**Comment by peterjc** [comment]
Adding @hugovk to the PyPI maintainers makes sense as a regular contributor 👍 

If you wanted to further reduce the "bus factor", I'd be willing to be a backup (same username https://pypi.org/user/peterjc/ on PyPI), something I ought to think about for my own flake8 plugins.

**Comment by peterjc** [comment]
Thanks - I'm on the project PyPI now, and I see Hugo's been invited too.

**Comment by hugovk** [comment]
Great! I'd emailed keisheiled, and I this repo has been moved to a new org. 👍 

I'll prep for a release, make a release checklist then do a release.

We can also automate releases via GitHub Actions, but we can think about that in the future if necessary.

**Comment by hugovk** [comment]
Draft release checklist:

https://github.com/hugovk/flake8-implicit-str-concat/blob/release-checklist/RELEASING.md

Will do the release, and make adjustments as needed.

**Comment by hugovk** [comment]
0.3.0 released! 🚀 

https://pypi.org/project/flake8-implicit-str-concat/0.3.0/

Also bumped the flit version https://github.com/flake8-implicit-str-concat/flake8-implicit-str-concat/commit/babe69da188f019dd780ef6996c69b6410b12c69 to include the fix for https://github.com/pypa/flit/issues/216:

```console
$ twine check --strict dist/*
Checking dist/flake8_implicit_str_concat-0.3.0-py2.py3-none-any.whl: PASSED
Checking dist/flake8_implicit_str_concat-0.3.0.tar.gz: FAILED, due to warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
  warning: `long_description` missing.
```

Thank all!
